apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: anomaly-detector-data
  namespace: airflow
  labels:
    app: anomaly-detector
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 5Gi
  # storageClassName: your-storage-class  # раскомментировать если нужен конкретный класс
