apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: anomaly-detector-data
  namespace: {{ .Values.namespace }}
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: {{ .Values.storage.data.size }}
  storageClassName: {{ .Values.storage.className }}
